
CREATE TABLE Document (
    ID NUMBER(18,0) NOT NULL,
    TITLE VARCHAR(64) NOT NULL,
    CONTENT VARCHAR(1024) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DOCUMENT_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807;

CREATE TABLE MST_USER
(
    USER_ID    NUMBER(9) NOT NULL,
    USER_CODE  VARCHAR2(20) NOT NULL,
    USER_NAME  VARCHAR2(200) NOT NULL,
    REGISTER_USER         VARCHAR2(20) NOT NULL,
    REGISTER_DATETIME     DATE NOT NULL,
    UPDATE_USER           VARCHAR2(20) NOT NULL,
    UPDATE_DATETIME       DATE NOT NULL,
    VERSION_NO            NUMBER(8) NOT NULL
)
;

CREATE TABLE MST_USER_ROLE
(
    USER_ROLE_ID      NUMBER(9) NOT NULL,
    USER_ID           NUMBER(9) NOT NULL,
    ROLE_ID           NUMBER(9) NOT NULL,
    REGISTER_USER         VARCHAR2(20) NOT NULL,
    REGISTER_DATETIME     DATE NOT NULL,
    UPDATE_USER           VARCHAR2(20) NOT NULL,
    UPDATE_DATETIME       DATE NOT NULL,
    VERSION_NO            NUMBER(8) NOT NULL
)
;

CREATE TABLE MST_ROLE
(
    ROLE_ID    NUMBER(9) NOT NULL,
    ROLE_NAME  VARCHAR2(200) NOT NULL,
    REGISTER_USER         VARCHAR2(20) NOT NULL,
    REGISTER_DATETIME     DATE NOT NULL,
    UPDATE_USER           VARCHAR2(20) NOT NULL,
    UPDATE_DATETIME       DATE NOT NULL,
    VERSION_NO            NUMBER(8) NOT NULL
)
;

-- ADD PK
ALTER TABLE MST_ROLE ADD CONSTRAINT PK_MST_ROLE 
    PRIMARY KEY (ROLE_ID)
;

ALTER TABLE MST_USER_ROLE ADD CONSTRAINT PK_MST_USER_ROLE
    PRIMARY KEY (USER_ROLE_ID)
;

ALTER TABLE MST_USER ADD CONSTRAINT PK_MST_USER 
    PRIMARY KEY (USER_ID)
;

-- ADD FK
ALTER TABLE MST_USER_ROLE ADD CONSTRAINT FK_USER_ROLE_MST_USER
    FOREIGN KEY (USER_ID) REFERENCES MST_USER (USER_ID)
;
ALTER TABLE MST_USER_ROLE ADD CONSTRAINT FK_USER_ROLE_MST_ROLE
    FOREIGN KEY (ROLE_ID) REFERENCES MST_ROLE (ROLE_ID)
;
